// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jkV7rXwHgreu0UI6dJAq3zY7KUKZzsk',
    appId: '1:245355978029:web:9c9e63a0e2d4538173c7a4',
    messagingSenderId: '245355978029',
    projectId: 'projectlogin-75ac5',
    authDomain: 'projectlogin-75ac5.firebaseapp.com',
    storageBucket: 'projectlogin-75ac5.appspot.com',
    measurementId: 'G-6MNE0FK5YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRzxIgWRZcvVF8VbjpZ9zZ0JC_NEwuEhk',
    appId: '1:245355978029:android:8324fb2d86bc03ca73c7a4',
    messagingSenderId: '245355978029',
    projectId: 'projectlogin-75ac5',
    storageBucket: 'projectlogin-75ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJgPBEegB5SM6yokp3Y8SP4qb5d06sOU',
    appId: '1:245355978029:ios:870f3de39639185473c7a4',
    messagingSenderId: '245355978029',
    projectId: 'projectlogin-75ac5',
    storageBucket: 'projectlogin-75ac5.appspot.com',
    iosClientId: '245355978029-9kgasvtkq1lk426aecuahls596tbqsnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJgPBEegB5SM6yokp3Y8SP4qb5d06sOU',
    appId: '1:245355978029:ios:870f3de39639185473c7a4',
    messagingSenderId: '245355978029',
    projectId: 'projectlogin-75ac5',
    storageBucket: 'projectlogin-75ac5.appspot.com',
    iosClientId: '245355978029-9kgasvtkq1lk426aecuahls596tbqsnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication14',
  );
}
